### ISSUE TITLE
Ordre du fichier README.md

### ISSUE THREAD

**Issue by jlegrand-79** [WildCodeSchool/2022_09_PHP_Lyon_Goldfish#52]
indiquer l'installation de extension=php_intl.dll avant d'ouvrir le serveur local

il faut aussi installer les extensions
sudo apt install php-xml php-mbstring php-intl
cette commande marche sur ubuntu
(trouver l'équivalent pour Windows)

bien préciser qu'il faut faire les 2 !

---

Préciser les accès admin
superman@mail.fr
super

**Comment by Eldohir** [comment]
ok corrigé !
