### ISSUE TITLE
Champ url de la table artist

### ISSUE THREAD

**Issue by Jottundr** [WildCodeSchool/2022_09_PHP_Lyon_Goldfish#59]
J'ai essayé d'ajouter un artiste avec une url plus longue que prévue dans votre formulaire et j'a un message d'erreur SQL qui pop. Je pense que ce serai mieux de montrer un message personnalisé pour mieux  comprendre l'erreur
![Capture d’écran du 2022-11-21 10-34-18](https://user-images.githubusercontent.com/115634102/203017353-4b5c9664-a0e6-40d4-ada8-887dd1d6b84d.png)

**Comment by JonasJallet** [comment]
resolved
