### ISSUE TITLE
Je peux po supprimer d'artistes :(

### ISSUE THREAD

**Issue by charlietoussaint** [WildCodeSchool/2022_09_PHP_Lyon_Goldfish#62]
Code erreur : PDOException (23000)
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`goldfish`.`favorite_concert`, CONSTRAINT `fk_favorite_concert` FOREIGN KEY (`favorite_concert_id`) REFERENCES `concert` (`id`))

**Comment by charlietoussaint** [comment]
Ca marche non depuis les concerts pour supp un artiste

**Comment by NinaSwoop** [comment]
Ok résolu

**Comment by JonasJallet** [comment]
resolve
