### ISSUE TITLE
modif en admin - pb adresse

### ISSUE THREAD

**Issue by 79Inaf** [WildCodeSchool/2022_09_PHP_Lyon_Goldfish#67]
Lorsqu'on modifie 'une salle de concert pour l'adresse, n'est enregistré que le numéro de rue et pas son nom

**Comment by 79Inaf** [comment]
capture écran du formulaire de  modif :
![Capture d’écran du 2022-11-21 11-17-08](https://user-images.githubusercontent.com/83811275/203025348-f54a23d0-63c9-46b8-9f4b-dc1574d9f0cd.png)

Résultat de la modif sans le nom de la rue : 

![Capture d’écran du 2022-11-21 11-18-12](https://user-images.githubusercontent.com/83811275/203025494-e3f4e99a-8378-4b93-808e-ae0ee326e25f.png)

**Comment by JonasJallet** [comment]
resolve
