### ISSUE TITLE
création d'un lieu

### ISSUE THREAD

**Issue by jlegrand-79** [WildCodeSchool/2022_09_PHP_Lyon_Goldfish#70]
Voir message d'erreur SQL quand on saisit un url image trop long

data:image/jpg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx4BBQUFBwYHDggIDh4UERQeHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHv/AABEIAE8A4gMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APQdKWVb2HzZoZop5sqgbBBx9056Grun2iJqt9Fh4gJ/mPIGMD71ZF1bW8E6CImSe2GVXbgbuvfqefar2k6ukt3rFs99DJC2CzEcIdo6mmId4/1COLwHrUcEyShonGS3fHb3rqZrhP7Mt3yhzApDe+Ofoa8r8cvZyeArt47iKKaKPYgSXcHB7DH9a29Ivb6LRpbSeaKb/R1YKwO8Hbnv/SqFc7ayidZdrKuNuTg47VPc/ZfKEhO0/wB6uJ0rXJYbCa7eSQEQBEV+CTkYz6mqt54qe6ja3uEMTKm4FB0b0/KlYOY7wRRs37y4WQ9gxByKr3kLgFrcnZgkrkbh/u+v0rgT4ihh1GOOGV4yFVzCYi2cjPy+meP8afbeNQLxo7xJIBwQfLO4deoPb6Z+vWgTZ0zX2pRwM8trEYAuVuFJA/4FzxXOWmpz3K7YJo7lzcOFiAKRnbjLbv4vXHvVt9StnlW8tLxTIQQ4WQGOQe+Oh9yD6c9KyrDU7iLWSx+xT3Mhlb5mKhE3lRjHbIP681SRDZrzNKQPNjIbrgYOD/WqzXE2MADHYiq2q6/ZG8FrNdxwqcbjGMvj6n+mavmzsmti+nMZAAD88g3nPqOv+H4UAmUZLpxkFc4psd2GOCStVZZiHwVjYA4JDU4NEcYVQaTC5fa5iRMtCX9yeKrXLQ3KBCQE6sMcH25/zxVK4Jbq3AohDMAFjYj1ANIpMvDTXjVpba5jglxkSBACPqBjj2qhPfRz7oZbhFuIvvJD84PH3hnt/Lp71DqisyNv+RAP42bH865TXGnS2Ux3SGSM5hcAcHHGCf5HgcdqCrlvUWu1vofsV3Nb+UrnbchGRk4BKqOV5PXt6c1jWwhufFZey1DzJ4bZd0PlBjuLvj5uF27cc56EY9BSv7rWZ7lTeWzwgRFJLlZeH7nIJAHbrxwe+Ky7S4ntPEZg0pBuCKyEMrhCCc55we/yms+YZ6D/AGZqF5Eba4doIY3+ZU5EjcE84GBz759a29PsAqLHPbSRlcD5kBXHrnpWJoGqXFvbSSTvEIz82ChXGexBGK2Rr10cQ21tLGGwVk4OR7AH5eo+9j6VsrCOkiiZIFYSARoOMKAKorf388jWun26y9N8hJWNc++OfWof9PuYVSWN5IW4LGVQMepHepDqoG+zs7N5GRcHbKAoPqWx/jV2C5Q1qxvbu582/vBcsqDyoi22IerbR1rJu7i1kvBZwSR20EK4eUKoaRvbuMe2a19SYNafatTmuEVhj7NbD757Bjxn+QpbWztILEy3EbWgC/LbwsWdgefmI+8fbpUtFIw2sb68uzDaRqI3XPnui45/2c5/E1mXmhSvL9nmkS5SE/v/ALMhClfQkE8/jXW3r2VnZeYLL95J8xWc7goPfAIyw9OlYlx4gjkljstF09rmZWys06gRxN/e2jPH1rKQy9BpemrCgj8Kw7AoC5LE4x/u0tUm0zV3YvL4pvA7HLBTgZ74+XpRWd2Udd4Z0aa48NIdXF0ks8e9cLna38JzwelcLqmpXFjdWc0lpuFw7JNBEwj3ENgEk98exqgJdUkshcnXbhUBCowc4/nxisTVre+XXLSX+0fOWU5aQtuJYdM5P86iVVqwuWPc6rxZDBbaJfI19A+4EjacqARwoOBn8hW1o+oyLY2N9IYWgmQRq/l7d2RtI9j6difevKPEqx26LbMWldmZmZT8p46eldTbySaXoMMNos0cE2x/KQqwD5BVgApxg4OeKpVmJwXc6qw1O31Yw6esRMkIUs/mdeCAMdevJHt2qzq1tFZ2txcLNCHjUEqGA3joQOM55zj29q808Oa/qGl6ZefZ9gm+0BrgumPlJrpzqFrf6VcC9uWs5ijSRbEBjUbSASQQRkj07041YtPUlxsy9qd5FaSWjwmSfzLeM/K2GVio4/A55qtDcX1wTIlvOJd48rzUL4P0xz05z/8Aq5rwq7axdRadI8fmkqQWYLwoyck9D757d662xvNPt7qe1UzXJV1V3huxwT7jKmnConqTKJv+HNItr2UHUYk0i6lOxZPOAtpTx8uRwrZ/hOPbPSqeh+HrF7W6n8hJGu7q4Jk3yK6qjkFvlwcLgdR1x0rMvZLK8YxWFmXhIAkeR1V8555AAfv1x16isvwVBerDOj6dZtbrLLG5Mz7nIkbgrkoVB6ZBHXrWvtFcmx1NpppjgC6NZ3LArl5LqH5Af7zN/Eep4P1xxWhpfhfVL2RWm1a3kRU+UIPlAORkBc4/M9j7VY0zxLPZxqpsbaZkI+ee6aRuPqMj8zTp/G1354b7LAqYwohchhj8eabqRIsUta0a60m0e7njeW2iZRuWQKGBOBjPPf0rDXUwnMds+D0zPkf+g1v6/rP9q6IIVumw8gYxOPmJB+p9K8vMEb6jeJNeiBUlk2l8EE5bAGT64rKpKSdkaRSsda+rtnHlxqx5GXP+FVY9d1SC7M6alamMrs+zGIYzn72d2c/jj2rmUttPEkSyagREY93mL5f3s9On40s1ho5/d/2tj5yd524z1x9314rNub6lrl7HS3+pz3rb55bMDbng7vyB4/nVZUmS7DpfqAVwCEy7DnIznIFczLYaWIGU6kS5zlVKY4AxzjHJ4q54JhH+nvgkAoWB2nOAfTrUOc1uy7J9Dp9X0O2e2fy9zseGkkkPcZwCv5/WuSXR4LTxahhU7Rp0ckq25MTnc+0kY6Ec9a7yPxBYzH9zDMkjYy8lsqr+jHH4CsrTmgufiRe5Wa4luNIjIygUZErHnsFxXS3F2sY2aG2Hh2xu4tya88gcthZCx2tnuO5+grWs/Dt9brhLyfK8K0Ui7T9QRx+YrpYp40cN9mRTjnaqnP445q1byqW3Rq8R68RgE/mK1UQuYENvdRgLdWEvk/deeEn5j7rk1qW4tEjNvZtGd3LYBAX25rTtoJrh5IvLuWTq7ZPB65+nvVk6bdXESxzQwpbjlQz43fh1NU2NNWuczc29sWaeTUHYRKdojj6H65/lVa0u4jbsQ0kLOPljiz5h9yxzgVP408RaB4UWG31O6V5/vC0s03FR/ebccCqng3xN4U8R3f2OyuLm21I5dUnULv8AoR1+lS3Hl5r6eht7Gra7j579O/oMu4Gewa2itpX35LlIjx7k9TUEE1rZ2bxRIyh+uWxk++K7QWFqror6jdFXyCWbIWmy+GrGQF7ISyP94h8AN75xwKTcbXIXM9LHnJ1W0yd0bZ7/AL1v8KKu3l5psF3NC0duTHIykhgRwcdaKjnpl2OTstQ05dCVFX7QgYbYSuSv4VgX0tjcteSbmtAoGUCH5OOtdbFpaXk9vfaZZrY2yglkPy7/AEJ9KzNdl0i3kwyxKXP70RRlg/1JrmVJ21JdRJ2uZGpG1Ph2KWzxIgGN+CCSTjP0rqGuIzpNiI9Qi8wBA0wAORx8v9K47WZ7VtHjS3huYlckKmMKOe9dHounXNxpCT3EIsbOOMMhmQLvYdMf44rTkYudEV0VS9mtXggEV5gPI2AEGeSf0rd1WLTI9EmUyiSKO3+ZUHLYwAf5ccetVtM1Xw5p2j28uuw21xdMxCIw3MwzwfQD3PWqmp6t4G1W0uo20M6fM5DLOlsN6/NgsMH7pxjP5ZqY0dXcTq9jlzFbzX9uHlnt7WbHmGNd0q+m3OOfriqk+oT6JdixeWK5gm+cSxgqxUNgbuOHBAPHH512nhbxn4fW0t10GS+sLe1YC4BuWEck3YbSDuBHPrVTxN4s0S/8WwXloNMn1VmUNqDo5jgIGAME7SQDz8pPTBNS8PbVSGpyb5UjU0bT7O0sYbvWrRba0miEbEy5OHcEE56c44//AFV1fgeDTzoV6FWFohqNyWZsEABhg9OOAK8+1fxLZ6ZodvDZazHfancXGw4mkjjhJbqyKNuD2HJ68cV0PhHV9F0jwley3etxSSJcziaFI5yrc4GG2jG7PU847cYraml0HWpzp6zW/wDX3HcWGoaJqHGn3djdSeX5mIWVm29M8dveo9V0201ARG7i3+UdyAheM/hXLeCrvWHgbVLGJdbhlkaCKOKWKGGLGCU+Zy3GR83HvnpV9dbnNxqLNqOlGE3LCBfPw0WMjyznIOCvUcZzVuEpaIwulqzSSxigtIrSJW8mFcIM/wBa8j8Yf2jb+JL9bKa3CrcPgNGGI5J9a6STxjqyeOLbSle1urYxlZI43X53KlgwbtjA4571T1mxu77VJ7vYqiWUyEeZ0zn/ABrOcHF6lxkmrnmt54q8Q215LZ+dbnyTgHyF9M/1ph8SeIMBmdSrHP8AqQATn6V0l14CurnU7m9N9tMxz5YiyF4Hfdz+QpP+EDv1bIvGcdMFBj9DUcqGZVhe65fWn2gXMSBmxjyl7Yr0n4ZWk0um30l24mlaVUJGBgbfb61g6N4YnsrD7KWAAcspC8YJ6YzXY+Flk0mC5RlF0rvvxHuU9Mf3fQE/p3FS6bexXMluaNvo9tb4MRlyoOMtntisPVbqSy8YPOZo4XOmRopm+Vf9cQFJHTJwOlbGo+JbOy0+e8kt5kMUe/ySrbiM4HO0Drnjt16GvO7m+XxHrtne6oxtobiBXMcbjaDG+QOc8AqSQfenGEosU5Jo9Ms729tLiKG6aG3MgJz9p+b2KjaO59q3dEttUluZdUXUWutOmWM23lS+YnTn2IPqK8ob4iHTNZm0Y2Mzu0bM0lwf3siYJBBGcqeceg9OlLoM2n6zfzoPFms+HYzGGhgjuDFBGAANq7gMH2+tbz5txQ93ZHaeK/F+sWGq6lpiNps0cqBId0W2WE/xZyBk+mM1xV5458YW07ywXkyR2yndiP5OfXI5/Guv8P8Ag3wfc6HqN1qeoatqeqJk2z/2iQ8/GcfLke3WuXvvCWl3FoZEsfEemyC2M0hk1ISICGIKbWUckc5z3rFqqrNmqcLNW3OU1y08Q+JZzrklre3c0qjzDgncR3HqOau+EtG1Xw7q1r4j1Sza3jtW3okoI3t2z6Cuq0vRdLPhudtB1jWLaK6PlySvOsxTaeQuAAp46jr70/Q/BxuJoLG/8Q61cWS7nldrhUZgASF+b8K61Vr+w9lfT9O39a+Zt9bjz8/Lra3/AAf608jY0rxVr6IuuPdW89lcsypEIs+W3oB171g+K/Guuazp8iW15P5JcxukabDwcEYqxdeCbmw1e31LTZLyOOFxMonvomxHnPBX5s9OAK6ObxDe3U8O/T7wmBgTLFfFfM9mGOR9a4HSk1yyk0YRtayieRLa3IUAGQDHdDmivXn125Z2b+yLzk5/hpaj6iv+fhpaXY8T1vx5q96bi40q1ijso324ZyS3PYDpXPWmp38l7Gj3r6d9pceZKrHCAnliBycdcV6iPDPh1W+XQYynX5l7/wBauxWllbjZaafbQnGMpEoNb+2TM+SxW1O88GaZ4NmsoXg1W8njT7NdzXRkfIcFtgwOODwRxzWj4j8b+H00XS9Og8OwvdXcUcaYBikG1QGcnrtBH41zXinSbCSxkupI2E1uBsIwAMnnIHXrUml+GvDdqsF8dKE92yKwmkmdiDj0zirVVEOm2ZN54u0hdLii8y0SVC6qs0YkljOe2PXFc9e3eqapt8uC6vkmRYpi1vIpVFclQh4wPmJr1Szure0XbbadpsfriDa31zn+lW11q4CELHCD0BUEfqDVKtEz9nNHHfCjw1b21teNe6O8rzeW6NOhAUY+6AeMjufwrvP7EsIoykmm6VCjDHzhBkH3xWRc6jfzZ3TyY/3jVRhI43SSEntxUSnF7IpKXVmsIfDdq+f7M0eMj+KK2jz+YH9ax/DFv4WaOZ7mxspLj7VIE8yEE7M8D6U/7LJMPnhVx/tp/jU1pobyH97sRTxtiTaMe56n+XtWd5uWlvxLaj3NP7J4ZnJT+zbBwg248hcDHOOB69qrX/hzw1eAb9KhjC5AEBaIf+OEZrStdNjgjwiIFHtxU7xKB8o4rdaGdjIsNI0bTU26fp8MLf3sFn/76bJx7ZqwT/dUZ9hVlo1HRRnsaLe2V9886MbeIZcrxnOcKD6n9MH0oAhDbEDEOHblMDgg5Gf8Px9qjDEpux8ucbu2fTNOmLSytIwBLHt0HsPYVNBeX8Fs0ENzIsJbcY8/KT3yKkor7hjkiodQsYb+GNJ5rqF4ydklvcNE2Djg46jIzzW1ql9It5PFZvELSWMLsSFVGCASOgPXNZpU+9IpGYnh61bzEutR1S9glXaYrq5Mi4z6Ef5xXPXvhLTY/EkGlWlzf2kFyrTF1mBeN+eFOOnyjrXYXUTrFhHZGY5DDv7Z/KsWexu5NTiv1ulM0P3d46deOnuah1HHoWoJjk+G3hq5Vvt82pXM7qF88XAVwB0HQjA+grlvEWnJZanJpkE2oRwWZ2QySyhmZcds8EfgK7+1ubhz/pRZcfxRnpWb4l8PPrEy3kGozJMi42uoKN9Rj9aca+uo3SdtDG8DaleaNrqPp8txcmXIlUwhQoGMH7x3ZzzwK9Ju/Ed6JGkBu7ndwVFkWX8ccV5DLpet22o20T+bYHzRtu4SGTI5GGPToOoro/CHxKksSNO1mKG+gy3DZ4cnn5hnvXZTnE55wa3OotUsZtTintRd6VNNIPtsSQOkN2vo6j5c9g1YMPh/XLrVWGp3Ef8AZgJZUhk2yAg5HbjtzVzQ/HFhqXiWOws33hiSArjAA7c9aiXxlZDWW0ee3Zroy7VGRjA68DrU1LdC4vXU2xpakxudV1D5DwrXJOfZsAZ/HNW73UIbC1M87KEHygNjk+lVpL6KVMKJEPcE7h+dYni63j1bS0gnimdUffiJsMRXMtzdsuHxBNk4022I+i/4UV5tcxEXMohg1nyg5Cbl5xnjNLW9qPYxvM9BWSFvvb0/3lxTJ2tV+/dxx8Z5YD+dZp06EHJQMPd2J/mBWxo48OWkavNoAuZerNIylfyrh9k2bc9jLkudLGVa6idm5PG7+lQ/abUE+TBdy56lIiq/ma63+0vC8zFjo6QDr8sQGPpinwy+E5sGNJEz0wrAmq9iiHUZygnu5ABBpzgDoZ5hj9KesF/N9/7PB/1zj3fzIrsoNN0K55iuZ8N0GT1/Kp/+EdteqXcoA/h2g1appEOozkobFlABclh1JOM/lVyC1UY3EE+vU1upoAYny77HP8UZ/wAadH4eu3+aGeJl77sg1aSJ5jLQRJwASfap42OMY/DvWivh2/A+UQse2H6/mKX+xtRjGWgwO5Dg4/WqSEVQG4Zj+tMl6VPJBLC2x0wfqKryNHuILMT6Yp2AjhhluLiOGBGkldgqKvUnNO1WSIFbK1fdBCfmf/nq/dvp2Ht9TV6Eiy0w3illubotDBt/gQffb6nIA+p9qyY14xwD7elAEZFHFT+WccAYpFTJqSkRAAdBxTwAf/11KI179aeIkxnFBRX29RwQexHFI9ojDKDHtipwnzcMDUmAMA5zSauWtDPZGXqPyFOAq+6J/ECT64warXUJGGihMijqAQD+GeKzlGxomVpUjeNkli8xW4II61zt74B8N3T+fBay6fOTnzLeUqc/TOK3BPKzSC3EUm3rGwIYfj0/WojfPDIFubSMZ7Bjn+eKzc3Evk5jn/D/AMO7TT/FNnqceq3E5hdn2yqrZJUjrj3ptp4Q+x+IbrVg0csr3DyRtswyZYnrXZ6MReXAktrVkAJyfN6f59qjWS3ctuldGDHPGapVtNyfY6lZH2xBZo5i+OHXGD+GM/rTUmjH+tEiHsdmf5VbCQk4W6IJ7NHnNONhI+QssRHXoVqFVRTplT7TH/f/APHD/jRVv+yrzsYsUU/aruL2bP/Z

**Comment by NinaSwoop** [comment]
Je n'arrive pas à reproduire le bug

**Comment by jlegrand-79** [comment]
![image](https://user-images.githubusercontent.com/103638673/203154627-8aa90e75-e576-42a5-8f40-11fa99358296.png)

**Comment by jlegrand-79** [comment]
mais vous embêtez pas avec ça, il vaudra mieux faire un upload ensuite

**Comment by JonasJallet** [comment]
resolved
